// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc841.MyRobot;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Encoder driveTrainLeftQuad2;
    public static Encoder driveTrainRightQuad1;
    public static WPI_TalonSRX driveTrainLeftDrive1;
    public static WPI_TalonSRX driveTrainLeftDrive2;
    public static WPI_TalonSRX driveTrainLeftDrive3;
    public static WPI_TalonSRX driveTrainRightDrive1;
    public static WPI_TalonSRX driveTrainRightDrive2;
    public static WPI_TalonSRX driveTrainRightDrive3;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainLeftQuad2 = new Encoder(2, 3, false, EncodingType.k4X);
        LiveWindow.addSensor("DriveTrain", "LeftQuad 2", driveTrainLeftQuad2);
        driveTrainLeftQuad2.setDistancePerPulse(1.0);
        driveTrainLeftQuad2.setPIDSourceType(PIDSourceType.kRate);
        driveTrainRightQuad1 = new Encoder(0, 1, false, EncodingType.k4X);
        LiveWindow.addSensor("DriveTrain", "RightQuad 1", driveTrainRightQuad1);
        driveTrainRightQuad1.setDistancePerPulse(1.0);
        driveTrainRightQuad1.setPIDSourceType(PIDSourceType.kRate);
        driveTrainLeftDrive1 = new WPI_TalonSRX(6);
        
        
        driveTrainLeftDrive2 = new WPI_TalonSRX(5);
        
        
        driveTrainLeftDrive3 = new WPI_TalonSRX(4);
        
        
        driveTrainRightDrive1 = new WPI_TalonSRX(1);
        
        
        driveTrainRightDrive2 = new WPI_TalonSRX(2);
        
        
        driveTrainRightDrive3 = new WPI_TalonSRX(3);
        
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
